### ISSUE TITLE
Can't preserve files' special permission bits

### ISSUE THREAD

**Issue by yurtk** [exaexa/chownmap#1]
Fix attached:
[chownmap.diff.txt](https://github.com/exaexa/chownmap/files/544280/chownmap.diff.txt)

**Comment by exaexa** [comment]
How does the fix actually help to preseve the _extended_ attributes? It seems much more like setting the standard r/w/x attributes, that aren't actually changed in the process, so it seems unnecessary to me.

Is there an use case I've missed, or something that is broken without this fix?

**Comment by yurtk** [comment]
Oh, sorry, I mean not _extended_ attributes, but _special_ permission bits: SUID, SGID.
After migration to LXD container I found special bits disappeared in many files.
E.g. _s_ bit disappears after chownmap:
-r-s--x--- 1 root apache    13984 Jul 18 18:24 suexec
-rwxr-sr-x 1 root smmsp    833544 Jul 12 18:45 sendmail.sendmail

**Comment by exaexa** [comment]
Kindof resurrecting the bug, is there any good way to preserve the bits?

**Comment by exaexa** [comment]
I've added some permission checking and chmodding and it seems fixed to me now, please reopen if there are any more problems with this.
